import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MiColectivo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-neutral-800 text-white ${inter.className}`}>
        <Header />
        <main className="xl:w-[1200px] xl:px-0 px-6 mx-auto">{children}</main>
      </body>
    </html>
  );
}
